### PR TITLE
Add ignore property

### PR DESCRIPTION
**Pull request by guybedford**
This removes unnecessary files from the package install, which also makes the jspm processing of the package easier.

### CODE REVIEW

**Comment by feross** [comment]
I'm -1 on this. It's a non-standard `package.json` property, as far as I can tell. Why doesn't jspm work like npm and use `.npmignore` or `.gitignore`?

**Comment by guybedford** [comment]
I completely forgot that npm doesn't support the `ignore` field here. I've added a `.npmignore` instead but let me know if you have another preference here at all.

**Comment by feross** [comment]
@guybedford I'm not in favor of ignoring the test folder. The test folder is documentation, and when I'm offline, I enjoy being able to look in `/node_modules/base64-js/test/` to see examples.

I'll leave this open in case other maintainers have a different opinion.

**Comment by feross** [comment]
Related discussions:
https://github.com/nodejs/readable-stream/pull/100
https://github.com/substack/node-browserify/issues/1093
https://github.com/crypto-browserify/sha.js/issues/5

**Comment by guybedford** [comment]
@feross would you be open to just ignoring the `bench` folder?

**Comment by guybedford** [comment]
@feross do you think it might still be possible to get movement on just a `bench` folder ignore as included here?

**Comment by feross** [comment]
Sure, I don't see the harm.

**Comment by feross** [comment]
Released as 1.0.2.

**Comment by guybedford** [comment]
Excellent, thanks so much!

**Pull request merged**
