### PR TITLE
Initialize package function as IIFE

### PR DESCRIPTION
**Pull request by fanatid**

### CODE REVIEW

**Comment by feross** [comment]
I actually don't think there's a need for an IIFE or an `init` function. This was in place before we offered a built file, so that we would not pollute the global namespace. Let's just execute the code in the normal scope.

**Comment by feross** [comment]
@fanatid Once you update this PR, I'll merge and release a new version.

**Comment by fanatid** [comment]
@feross updated

**Comment by feross** [comment]
Released as 1.2.0

**Comment by fanatid** [comment]
Are you need PR to buffer? :)

**Comment by feross** [comment]
That would be excellent!

**Pull request merged**
