### PR TITLE
Some little changes in package.json

### PR DESCRIPTION
**Pull request by ZenanZha**
I fixed a spelling in package.json, so "Dependencies" is working right now. I also add some new Keywords. This is my first pull request. It is my pleasure if you can accept it. If you have any question, please tall to me.

### CODE REVIEW

**Comment by fanatid** [comment]
@ZenanZha you not right, should be `devDependencies`

**Comment by ZenanZha** [comment]
Sorry, but it is not working here.
https://www.npmjs.com/package/base64-js
screen shot 2017-01-26 at 2 51 12 pm

**Comment by fanatid** [comment]
because projects do not need any dependencies, devDependencies needed only for development (tests/linting/etc)

**Comment by ZenanZha** [comment]
I feel sorry for my mistake. I found out where I don't understand.
Thank you for your remind.

**Pull request closed without merging**
