### PR TITLE
fix: const & let to var

### PR DESCRIPTION
**Pull request by chenfengjw163**

### CODE REVIEW

**Comment by pashkes** [comment]
We have a chance for the PR merging today?

**Comment by afelicioni** [comment]
maybe @feross can helpas he published affected build some hours ago, also I see feross/buffer uses this package in their dependencies

**Comment by pashkes** [comment]
Maybe will be better do revert to the last release?

**Review by feross — APPROVED** [review]

**Comment by feross** [comment]
Released as 1.5.1

**Pull request merged**
