### PR TITLE
use xorshift.js in benchmark

### PR DESCRIPTION
**Pull request by fanatid**
`xorshift.js` give a chance use `seed` for generating same data every time

### CODE REVIEW

**Comment by feross** [comment]
Why is this useful? I don't understand.

**Comment by fanatid** [comment]
With random generator that supports seed you can run benchmarks with same data in different environments.

**Comment by feross** [comment]
Hmm, let me try it out.

**Comment by feross** [comment]
Do any other maintainers have thoughts about this?

I really don't understand why this is an issue. The data being different won't have a meaningful effect on the speed, will it?

**Comment by fanatid** [comment]
Hmm, you right, for `base64-js` different data (but with same length) will don't give significant effect.

**Pull request closed without merging**
